version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.10"
        # Optional Node.js version to install
        NODE_VERSION: "16"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sangtong@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tongdang
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      #- ../db:/var/lib/mysql
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-django}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4848:80  

volumes:
  local_pgdata:
  pgadmin-data:
  db-store:
